name       : calc
version    : 2.13.0.1
release    : 3
source     :
    - https://github.com/lcn2/calc/releases/download/v2.13.0.1/calc-2.13.0.1.tar.bz2 : 6ae538f57785c5701a70112ccf007ab5553abd332ae2deaadaf564f401c734ad
license    : LGPL-2.1-or-later
component  : office.maths
summary    : C-style arbitrary precision calculator
description: |
    C-style arbitrary precision calculator
build      : |
    %make -j1
install    : |
    %make_install T="$installdir"
